-- 1. Provide the list of markets in which customer "Atliq Exclusive" operates its business in the APAC region.

SELECT 
	DISTINCT MARKET
FROM
	DIM_CUSTOMER
WHERE REGION = 'APAC' 
	AND CUSTOMER = 'Atliq Exclusive';
    
-- 2. What is the percentage of unique product increase in 2021 vs. 2020?

WITH 
Products_2020 AS 
	(SELECT  COUNT(DISTINCT PRODUCT_CODE) AS "UNIQUE_PRODUCTS_2020" FROM FACT_SALES_MONTHLY WHERE FISCAL_YEAR =2020),
Products_2021 AS 
	(SELECT  COUNT(DISTINCT PRODUCT_CODE) AS "UNIQUE_PRODUCTS_2021" FROM FACT_SALES_MONTHLY WHERE FISCAL_YEAR =2021)
SELECT 
	P20.UNIQUE_PRODUCTS_2020, P21.UNIQUE_PRODUCTS_2021, 
	ROUND( ( (P21.UNIQUE_PRODUCTS_2021 - P20.UNIQUE_PRODUCTS_2020) *100 / P20.UNIQUE_PRODUCTS_2020) , 2) AS PERCENTAGE_CHG
FROM
	Products_2021 P21 CROSS JOIN Products_2020 P20 ;

-- 3. Provide a report with all the unique product counts for each segment and sort them in descending order of product counts

SELECT 
	SEGMENT, COUNT(DISTINCT PRODUCT_CODE) AS "PRODUCT_COUNT"
FROM 
	DIM_PRODUCT
GROUP BY SEGMENT
ORDER BY PRODUCT_COUNT DESC;

-- 4. Follow-up: Which segment had the most increase in unique products in 2021 vs 2020?

WITH 
PRODUCTS_2020 AS
 (SELECT SEGMENT, COUNT( DISTINCT P.PRODUCT_CODE) AS "product_count_2020" 
  FROM DIM_PRODUCT P JOIN FACT_SALES_MONTHLY FS 
  ON FS.PRODUCT_CODE= P.PRODUCT_CODE 
  WHERE FISCAL_YEAR = 2020 
  GROUP BY SEGMENT)
, PRODUCTS_2021 AS 
 (SELECT SEGMENT, COUNT(DISTINCT P.PRODUCT_CODE) AS "product_count_2021" 
 FROM DIM_PRODUCT P JOIN FACT_SALES_MONTHLY FS 
 ON FS.PRODUCT_CODE= P.PRODUCT_CODE 
 WHERE FISCAL_YEAR = 2021 
 GROUP BY SEGMENT)

SELECT  
	P20.SEGMENT,  product_count_2021, product_count_2020,   
    (product_count_2021-product_count_2020) AS DIFFERENCE 
    FROM PRODUCTS_2020 P20  JOIN PRODUCTS_2021 P21
    ON P20.SEGMENT = P21.SEGMENT;

-- 5.Get the products that have the highest and lowest manufacturing costs

SELECT 
DP.PRODUCT_CODE, PRODUCT, MANUFACTURING_COST 
FROM DIM_PRODUCT DP JOIN FACT_MANUFACTURING_COST FM 
ON FM.PRODUCT_CODE = DP.PRODUCT_CODE 
WHERE MANUFACTURING_COST IN
 (
	(SELECT MAX(MANUFACTURING_COST) FROM fact_manufacturing_cost)
,
	(SELECT MIN(MANUFACTURING_COST) FROM fact_manufacturing_cost)
)
ORDER BY MANUFACTURING_COST DESC;


-- 6. Generate a report which contains the top 5 customers who received an average high pre_invoice_discount_pct 
-- for the fiscal year 2021 and in the Indian market??

SELECT 
	DC.CUSTOMER,  AVG(PRE_INVOICE_DISCOUNT_PCT) AS "AVERAGE_DISCOUNT_PERCENTAGE"
FROM FACT_PRE_INVOICE_DEDUCTIONS FINV JOIN DIM_CUSTOMER DC 
ON 
	DC.CUSTOMER_CODE= FINV.CUSTOMER_cODE
WHERE 
	FISCAL_YEAR=2021 AND MARKET = 'INDIA' 
GROUP BY 
	DC.CUSTOMER 
ORDER BY 
	AVERAGE_DISCOUNT_PERCENTAGE DESC 
LIMIT 5 ;


-- 7. Get the complete report of the Gross sales amount for the customer “AtliqExclusive” for each month. 
-- This analysis helps to get an idea of low and high-performing months and take strategic decisions

SELECT  
	DATE_FORMAT(DATE, '%M') AS MONTHS, GP.FISCAL_YEAR, 
	ROUND(SUM(SOLD_QUANTITY*GROSS_PRICE)/1000000,2) AS "GROSS SALES AMOUNT(Mlns)"  
FROM FACT_SALES_MONTHLY FS 
JOIN 
	FACT_GROSS_PRICE GP  
ON 
	FS.FISCAL_YEAR = GP.FISCAL_YEAR AND FS.PRODUCT_CODE= GP.PRODUCT_CODE
JOIN 
	DIM_CUSTOMER DC ON DC.CUSTOMER_CODE= FS.CUSTOMER_CODE	
WHERE 
	CUSTOMER = 'Atliq Exclusive'
GROUP BY 
	MONTHS, GP.FISCAL_YEAR
ORDER BY 
	GP.FISCAL_YEAR ASC;


-- 8. In which quarter of 2020, got the maximum total_sold_quantity?

SELECT  
	CONCAT('Q',quarter(DATE_ADD(DATE, INTERVAL 4 MONTH))) AS QUATER,
	SUM(SOLD_QUANTITY)/1000000 AS "TOTAL_SOLD_QUANTITY_Mlns" 
FROM 
	FACT_SALES_MONTHLY 
WHERE 
	FISCAL_YEAR=2020
GROUP BY 
	QUATER
 ORDER BY 
	TOTAL_SOLD_QUANTITY_Mlns DESC;


-- 9. Which channel helped to bring more gross sales in the fiscal year 2021 and the percentage of contribution?

WITH 
Gross_sales AS 
	(SELECT 
		CHANNEL,ROUND(SUM(SOLD_QUANTITY*GROSS_PRICE)/1000000,2) AS "GROSS_SALES_Mlns" 
	FROM 
		FACT_GROSS_PRICE GP 
	JOIN FACT_SALES_MONTHLY FS 
    ON 
		FS.FISCAL_YEAR=GP.FISCAL_YEAR AND FS.PRODUCT_CODE=GP.PRODUCT_CODE 
	JOIN DIM_CUSTOMER DC 
    ON 
		DC.CUSTOMER_CODE= FS.CUSTOMER_CODE 
	WHERE
		GP.FISCAL_YEAR=2021 GROUP BY CHANNEL)
,Total_sale AS 
	(SELECT SUM(GROSS_SALES_MLNS) AS "TOTAL_SALES_Mlns" 
	 FROM Gross_sales )
SELECT 
	CHANNEL, GROSS_SALES_MLNS,
    ROUND((GROSS_SALES_MLNS/TOTAL_SALES_Mlns)*100,2) AS "PERCENTAGE" 
FROM Gross_sales CROSS JOIN Total_sale
ORDER BY GROSS_SALES_MLNS DESC; 


-- 10. Get the Top 3 products in each division that have a high total_sold_quantity in the fiscal_year 2021?
WITH 
Division_sales AS
	(SELECT DIVISION, DP.PRODUCT_CODE, DP.PRODUCT, SUM(SOLD_QUANTITY) AS "TOTAL_SOLD_QUANTITY" 
    FROM DIM_PRODUCT DP JOIN FACT_SALES_MONTHLY FSM
	ON
		FSM.PRODUCT_CODE= DP.PRODUCT_CODE
	WHERE FSM.FISCAL_YEAR = 2021
	GROUP BY DP.DIVISION, DP.PRODUCT_CODE, DP.PRODUCT)
,
Sales_rank AS
	(SELECT *, DENSE_RANK() OVER(PARTITION BY DIVISION ORDER BY TOTAL_SOLD_QUANTITY DESC) S_rnk FROM Division_sales)
SELECT * FROM Sales_rank where S_rnk<=3;